# Abilities.yaml
# Contains all Abilities used by playable characters and enemies


Abilities:
    - Id                    : A0001 # Sword Auto Attack
      Name                  : Attack
      Description           : Default Attack
      Effects               :
        - E0001
      DefaultTarget         : SingleEnemy 
      TargetTypes           :
        - SingleEnemy
        - SingleAlly
        
    - Id                    : A0002 # Spear Auto Attack
      Name                  : Attack
      Description           : Default Attack
      Effects               :
        - E0002
      DefaultTarget         : SingleEnemy 
      TargetTypes           :
        - SingleEnemy
        - Enemies
        - SingleAlly
        - Allies
        

#Weapon Abilities
    - Id                    : AW0001
      Name                  : Sword thurst
      Description           : Attack an enemy with the tip of a blade
      AbilityType           : Weapon
      EquipmentRestrictrion : 
        - Short_Sword
      Effects               :
        - EW0001.1
      TargetTypes           :
        - SingleEnemy
      CastCost              :
        Stamina             : 5

    - Id                    : AW0002
      Name                  : Sword sweep
      Description           : Perform a powerful spin with a blade to strike all the enemies
      AbilityType           : Weapon
      EquipmentRestrictrion : 
        - Long_Sword
      Effects               :
        - EW0002.1
        - EW0003.1
      TargetTypes           :
        - Enemies
      CastCost              :
        Stamina             : 30

    - Id                    : AW0003
      Name                  : Spear point
      Description           : Perform a powerfull sping with a blade to strike all the enemies
      AbilityType           : Weapon
      EquipmentRestrictrion : 
        - Spear
      Effects               :
        - EW0004.1
      TargetTypes           :
        - SingleEnemy
      CastCost              :
        Stamina             : 13

    - Id                    : AW0004
      Name                  : Armor Pierce
      Description           : Perform a powerfull sping with a blade to strike all the enemies
      AbilityType           : Weapon
      EquipmentRestrictrion : 
        - Short_Sword
      Effects               :
        - EW0005.1
        - EW0006.1
      TargetTypes           :
        - SingleEnemy
      CastCost              :
        Stamina             : 8
    # Sword thurst
    - Id                    : AW0005.1
      Name                  : Sword thurst
      Description           : Attack an enemy with the tip of a blade
      AbilityType           : Weapon
      EquipmentRestrictrion : 
        - Short_Sword
      Effects               :
        - EW0001.1
      TargetTypes           :
        - SingleEnemy
      CastCost              :
        Stamina             : 5
    - Id                    : AW0005.2
      Name                  : Sword thurst
      Description           : Attack an enemy with the tip of a blade
      AbilityType           : Weapon
      EquipmentRestrictrion : 
        - Short_Sword
      Effects               :
        - EW0001.1
      TargetTypes           :
        - SingleEnemy
      CastCost              :
        Stamina             : 5
    - Id                    : AW0005.3
      Name                  : Sword thurst
      Description           : Attack an enemy with the tip of a blade
      AbilityType           : Weapon
      EquipmentRestrictrion : 
        - Short_Sword
      Effects               :
        - EW0001.1
      TargetTypes           :
        - SingleEnemy
      CastCost              :
        Stamina             : 5
    - Id                    : AW0005.4
      Name                  : Sword thurst
      Description           : Attack an enemy with the tip of a blade
      AbilityType           : Weapon
      EquipmentRestrictrion : 
        - Short_Sword
      Effects               :
        - EW0001.1
      TargetTypes           :
        - SingleEnemy
      CastCost              :
        Stamina             : 5
    - Id                    : AW0005.5
      Name                  : Sword thurst
      Description           : Attack an enemy with the tip of a blade
      AbilityType           : Weapon
      EquipmentRestrictrion : 
        - Short_Sword
      Effects               :
        - EW0001.1
      TargetTypes           :
        - SingleEnemy
      CastCost              :
        Stamina             : 5

#Talent Abilities 
    - Id                    : AT0001
      Name                  : Ralying Cry
      Description           : Shout loudly to raly allies and increase their defense
      AbilityType           : Talent
      Ranks                 :
        - Effects           :
            - ET0001.1
          TargetTypes       :
            - Allies
          CastCost          :
          Stamina           : 4
        - Effects           :
            - ET0001.2
          TargetTypes       :
            - Allies
          CastCost          :
          Stamina           : 4
        - Effects           :
            - ET0001.3
          TargetTypes       :
            - Allies
          CastCost          :
          Stamina           : 4
      Effects               :
        - ET0001.1
      TargetTypes           :
        - Allies
      CastCost              :
        Stamina             : 4

    - Id                    : AT0002
      Name                  : Fleet of foot
      Description           : Take up a stance to react more quickly
      AbilityType           : Talent
      Effects               :
        - ET0002.1
      TargetTypes           :
        - Allies
      CastCost              :
        Stamina             : 4

    - Id                    : AT0003
      Name                  : Sharpen Blade 
      Description           : 
      AbilityType           : Talent
      Effects               :
        - ET0003.1
      DefaultTarget         : Self
      CastCost              :
        Stamina             : 4

#Magic Abilities
    - Id                    : AM0001
      Name                  : Flame Ball
      Description           : Send a magically confured flame ball to the target.
      AbilityType           : AttackMagic
      Effects               :
        - EM0001.1
      DefaultTarget         : SingleEnemy 
      TargetTypes           :
        - SingleEnemy
        - Enemies
        - SingleAlly
        - Allies
      Backswing             : 2000
      CastCost              :
        MP                  : 8

    - Id                    : AM0002
      Name                  : Flame Thrower
      Description           : Unleash wide flames to the targets and reduce their fire resistance
      AbilityType           : AttackMagic
      Effects               :
        - EM0002.1
        - EM0003.1
      TargetTypes           :
        - SingleEnemy
      CastTime              : 2.0
      Backswing             : 1.0
      CastCost              :
        MP                  : 8

#Monster Abilities
    - Id                    : AMST0001
      Name                  : Bite
      AbilityType           : Monster
      Effects               :
        - EMST0001
      TargetTypes           :
        - SingleEnemy
    - Id                    : AMST0002
      Name                  : Shierk
      AbilityType           : Monster
      Effects               :
        - EMST0002
      TargetTypes           :
        - Enemies