# Enemies.yaml
# Contains all enemies of the game

EnemySpawners:
    - Id                     : EG0001
      Groups                 :
        - Probability        : 0.75
          EnemyReferences    :
           - EnemyID         : EN0001
             FrontRow        : true
        - Probability        : 0.25
          EnemyReferences     :
           - EnemyID         : EN0001
             FrontRow        : true
           - EnemyID         : EN0002
             FrontRow        : true
           - EnemyID         : EN0002
             FrontRow        : true
           - EnemyID         : EN0002
             FrontRow        : false

Enemies:
    - Id                    : EN0001
      Name                  : White Wolf
      Level                 : 3
      BaseAttributes        :
        MaxHP               : 5000
        MaxMP               : 0
        MaxStamina          : 10
        Attack              : 4
        Defense             : 5
        Magic               : 0
        Resistance          : 2
        Speed               : 50
      CombatThresholds      :
        - Threshold         : 100
          Abilities         :
            - Id            : AMST0002
              Probability   : 0.05
            - Id            : AMST0001
              Probability   : 0.95
      GoldBounty            : 12
      ExperienceBounty      : 200
      LootTable             :
        LootDrops           :
          - Id              : C0001
            Quantity        : 1
            Probability     : 1.0

    - Id                    : EN0002
      Name                  : Black Wolf
      Level                 : 3
      BaseAttributes        :
        MaxHP               : 24
        MaxMP               : 0
        MaxStamina          : 10
        Attack              : 7
        Defense             : 7
        Magic               : 2
        Resistance          : 4
      GoldBounty            : 10
      ExperienceBounty      : 10
      LootTable             :
        LootDrops           :
          - Id              : C0001
            Quantity        : 1
            Probability     : 0.7