# NPCs.yaml
GrowthTables:
    - CharacterId       : PC0001
      XPToNextLevel     :
        - 50
        - 80
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120

    - CharacterId       : PC0002
      XPToNextLevel     :
        - 50
        - 80
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120

    - CharacterId       : PC0003
      XPToNextLevel     :
        - 50
        - 80
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120

    - CharacterId       : PC0004
      XPToNextLevel     :
        - 50
        - 80
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120

    - CharacterId       : PC0005
      XPToNextLevel     :
        - 50
        - 80
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120
        - 120